# Generated by Django 5.2.8 on 2026-04-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_notice_post_userpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='active_menu',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='高亮菜单'),
        ),
        migrations.AddField(
            model_name='menu',
            name='always_show',
            field=models.BooleanField(default=True, verbose_name='是否总是显示'),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_affix',
            field=models.BooleanField(default=False, verbose_name='是否固定标签'),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_breadcrumb',
            field=models.BooleanField(default=True, verbose_name='是否显示面包屑'),
        ),
        migrations.AddField(
            model_name='menu',
            name='redirect',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='重定向地址'),
        ),
    ]
