# Generated by Django 5.2.8 on 2025-12-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='route_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='路由名称'),
        ),
    ]
