# Generated by Django 5.2.8 on 2025-12-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStudioTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('type', models.CharField(choices=[('data_integration', '数据采集'), ('hive', 'Hive计算'), ('spark', 'Spark计算'), ('flink', 'Flink计算'), ('python', 'Python脚本'), ('shell', 'Shell脚本')], max_length=50, verbose_name='任务类型')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='任务描述')),
                ('config', models.JSONField(default=dict, verbose_name='任务配置')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '停用')], default='0', max_length=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '数据开发任务',
                'verbose_name_plural': '数据开发任务',
                'db_table': 'datastudio_task',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['name'], name='datastudio__name_3c3f1e_idx'), models.Index(fields=['type'], name='datastudio__type_cf20ef_idx'), models.Index(fields=['status'], name='datastudio__status_2280e6_idx'), models.Index(fields=['del_flag'], name='datastudio__del_fla_e1125b_idx')],
            },
        ),
    ]
