# Generated by Django 5.2.8 on 2026-02-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastudio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastudiotask',
            name='type',
            field=models.CharField(choices=[('data_integration', '数据采集'), ('hive', 'Hive计算'), ('spark', 'Spark计算'), ('spark_sql', 'SparkSQL计算'), ('flink', 'Flink计算'), ('flink_sql', 'FlinkSQL计算'), ('python', 'Python脚本'), ('shell', 'Shell脚本')], max_length=50, verbose_name='任务类型'),
        ),
    ]
