# Generated by Django 5.2.8 on 2026-03-31 15:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=36, unique=True, verbose_name='Session ID')),
                ('status', models.CharField(choices=[('0', 'Connected'), ('1', 'Disconnected')], default='0', max_length=1, verbose_name='Status')),
                ('host', models.CharField(default='localhost', max_length=100, verbose_name='Host')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Terminal Session',
                'verbose_name_plural': 'Terminal Sessions',
                'db_table': 'terminal_session',
            },
        ),
        migrations.CreateModel(
            name='TerminalCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('command', models.TextField(verbose_name='Command')),
                ('output', models.TextField(blank=True, null=True, verbose_name='Output')),
                ('exit_code', models.IntegerField(blank=True, null=True, verbose_name='Exit Code')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='Execution Time (seconds)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='terminal.terminalsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Terminal Command',
                'verbose_name_plural': 'Terminal Commands',
                'db_table': 'terminal_command_history',
            },
        ),
        migrations.AddIndex(
            model_name='terminalsession',
            index=models.Index(fields=['user', 'status'], name='terminal_se_user_id_f2c757_idx'),
        ),
        migrations.AddIndex(
            model_name='terminalsession',
            index=models.Index(fields=['create_time'], name='terminal_se_create__75907f_idx'),
        ),
        migrations.AddIndex(
            model_name='terminalcommand',
            index=models.Index(fields=['session', 'create_time'], name='terminal_co_session_9f87a3_idx'),
        ),
        migrations.AddIndex(
            model_name='terminalcommand',
            index=models.Index(fields=['user', 'create_time'], name='terminal_co_user_id_aa809f_idx'),
        ),
    ]
