# Generated by Django 5.2.8 on 2026-02-05 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataasset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('task_name', models.CharField(help_text='ETL任务名称', max_length=128, verbose_name='任务名称')),
                ('task_code', models.CharField(help_text='唯一标识编码', max_length=64, unique=True, verbose_name='任务编码')),
                ('description', models.TextField(blank=True, help_text='任务描述信息', null=True, verbose_name='任务描述')),
                ('etl_type', models.CharField(choices=[('extract', 'STG采集'), ('transform', 'DWD转换'), ('load', 'ODS加载'), ('full', '全量ETL')], default='full', help_text='ETL任务类型', max_length=20, verbose_name='ETL类型')),
                ('executor_type', models.CharField(choices=[('mock', '模拟执行器'), ('datax', 'DataX'), ('spark', 'Spark SQL'), ('python', 'Python脚本')], default='mock', help_text='执行器类型', max_length=20, verbose_name='执行器类型')),
                ('execute_strategy', models.CharField(choices=[('full', '全量'), ('increment', '增量')], default='full', help_text='执行策略：全量或增量', max_length=20, verbose_name='执行策略')),
                ('target_table', models.CharField(help_text='目标表名', max_length=256, verbose_name='目标表')),
                ('sql_config', models.TextField(blank=True, help_text='SQL配置内容，支持采集、转换、加载SQL', null=True, verbose_name='SQL配置')),
                ('executor_params', models.JSONField(blank=True, help_text='执行器参数配置（JSON格式）', null=True, verbose_name='执行参数')),
                ('status', models.CharField(choices=[('0', '启用'), ('1', '停用')], default='0', help_text='任务状态：0-启用，1-停用', max_length=1, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('source_datasource', models.ForeignKey(help_text='源数据源', on_delete=django.db.models.deletion.PROTECT, related_name='source_etl_tasks', to='dataasset.datasource', verbose_name='源数据源')),
                ('source_table', models.ForeignKey(help_text='源表信息', on_delete=django.db.models.deletion.PROTECT, related_name='source_etl_tasks', to='dataasset.metatable', verbose_name='源表')),
                ('target_datasource', models.ForeignKey(help_text='目标数据源', on_delete=django.db.models.deletion.PROTECT, related_name='target_etl_tasks', to='dataasset.datasource', verbose_name='目标数据源')),
            ],
            options={
                'verbose_name': 'ETL任务',
                'verbose_name_plural': 'ETL任务',
                'db_table': 'dataetl_task',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ETLFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('source_field_name', models.CharField(help_text='源表字段名称', max_length=128, verbose_name='源字段名')),
                ('target_field_name', models.CharField(help_text='目标表字段名称', max_length=128, verbose_name='目标字段名')),
                ('transform_rule', models.CharField(blank=True, help_text='字段转换规则表达式', max_length=512, null=True, verbose_name='转换规则')),
                ('clean_rule', models.CharField(blank=True, help_text='数据清洗规则', max_length=512, null=True, verbose_name='清洗规则')),
                ('data_type', models.CharField(blank=True, help_text='字段数据类型', max_length=64, null=True, verbose_name='数据类型')),
                ('is_primary_key', models.BooleanField(default=False, help_text='是否为主键字段', verbose_name='是否主键')),
                ('sort_order', models.IntegerField(default=0, help_text='字段排序', verbose_name='排序')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('task', models.ForeignKey(help_text='关联的ETL任务', on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='dataetl.etltask', verbose_name='ETL任务')),
            ],
            options={
                'verbose_name': 'ETL字段映射',
                'verbose_name_plural': 'ETL字段映射',
                'db_table': 'dataetl_field_mapping',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ETLExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.CharField(help_text='唯一执行标识', max_length=64, unique=True, verbose_name='执行ID')),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('running', '执行中'), ('success', '执行成功'), ('failed', '执行失败'), ('cancelled', '已取消')], default='pending', help_text='执行状态', max_length=20, verbose_name='执行状态')),
                ('trigger_type', models.CharField(choices=[('manual', '手动触发'), ('schedule', '调度触发'), ('api', 'API触发')], default='manual', help_text='任务触发方式', max_length=20, verbose_name='触发方式')),
                ('start_time', models.DateTimeField(blank=True, help_text='任务开始执行时间', null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, help_text='任务结束时间', null=True, verbose_name='结束时间')),
                ('duration_seconds', models.IntegerField(blank=True, help_text='任务执行时长（秒）', null=True, verbose_name='执行时长(秒)')),
                ('total_rows', models.IntegerField(blank=True, help_text='处理的总行数', null=True, verbose_name='总行数')),
                ('success_rows', models.IntegerField(blank=True, help_text='成功处理的行数', null=True, verbose_name='成功行数')),
                ('failed_rows', models.IntegerField(blank=True, help_text='失败的行数', null=True, verbose_name='失败行数')),
                ('error_message', models.TextField(blank=True, help_text='执行失败时的错误信息', null=True, verbose_name='错误信息')),
                ('log_file', models.CharField(blank=True, help_text='日志文件路径', max_length=512, null=True, verbose_name='日志文件')),
                ('executed_by', models.CharField(blank=True, help_text='任务执行者', max_length=64, null=True, verbose_name='执行者')),
                ('executor_params', models.JSONField(blank=True, help_text='本次执行的参数快照', null=True, verbose_name='执行参数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(help_text='关联的ETL任务', on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='dataetl.etltask', verbose_name='ETL任务')),
            ],
            options={
                'verbose_name': 'ETL执行日志',
                'verbose_name_plural': 'ETL执行日志',
                'db_table': 'dataetl_execution_log',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ETLTaskVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(help_text='版本号', verbose_name='版本号')),
                ('config_snapshot', models.JSONField(help_text='任务配置快照（JSON格式）', verbose_name='配置快照')),
                ('change_log', models.TextField(help_text='版本变更说明', verbose_name='变更日志')),
                ('is_current', models.BooleanField(default=False, help_text='是否为当前使用的版本', verbose_name='当前版本')),
                ('create_by', models.CharField(blank=True, max_length=64, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(help_text='关联的ETL任务', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='dataetl.etltask', verbose_name='ETL任务')),
            ],
            options={
                'verbose_name': 'ETL任务版本',
                'verbose_name_plural': 'ETL任务版本',
                'db_table': 'dataetl_task_version',
                'ordering': ['-version_number'],
                'unique_together': {('task', 'version_number')},
            },
        ),
    ]
