# Generated by Django 5.2.8 on 2026-03-24 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataetl', '0001_initial'),
        ('datasource', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='etltask',
                    name='source_datasource',
                    field=models.ForeignKey(help_text='源数据源', on_delete=django.db.models.deletion.PROTECT, related_name='source_etl_tasks', to='datasource.datasource', verbose_name='源数据源'),
                ),
                migrations.AlterField(
                    model_name='etltask',
                    name='target_datasource',
                    field=models.ForeignKey(help_text='目标数据源', on_delete=django.db.models.deletion.PROTECT, related_name='target_etl_tasks', to='datasource.datasource', verbose_name='目标数据源'),
                ),
            ],
            database_operations=[],
        ),
    ]
