# Generated by Django 5.2.8 on 2026-02-05 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataasset', '0001_initial'),
        ('dataetl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etltask',
            name='source_table',
            field=models.ForeignKey(blank=True, help_text='源表信息', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_etl_tasks', to='dataasset.metatable', verbose_name='源表'),
        ),
    ]
