# Generated by Django 5.2.8 on 2025-12-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataetl', '0002_rename_dataintegra_name_5b2a4e_idx_dataintegra_name_f6db92_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationtask',
            name='type',
            field=models.CharField(choices=[('dbToDb', '数据库同步'), ('dbToHive', '数据库同步到Hive'), ('hiveToDb', 'Hive同步到数据库')], max_length=20, verbose_name='任务类型'),
        ),
    ]
