# Generated by Django 5.2.8 on 2026-03-25 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataasset', '0002_move_datasource'),
        ('dataetl', '0002_alter_etltask_source_datasource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etltask',
            name='source_database_name',
            field=models.CharField(blank=True, help_text='源数据库名称（多库场景）', max_length=256, null=True, verbose_name='源数据库名'),
        ),
        migrations.AddField(
            model_name='etltask',
            name='source_table_name',
            field=models.CharField(blank=True, help_text='直接指定的源表名称', max_length=256, null=True, verbose_name='源表名'),
        ),
        migrations.AlterField(
            model_name='etltask',
            name='source_table',
            field=models.ForeignKey(blank=True, help_text='源表信息（元数据关联）', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_etl_tasks', to='dataasset.metatable', verbose_name='源表'),
        ),
    ]
