# Generated by Django 5.2.8 on 2026-03-02 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataetl', '0002_alter_etltask_source_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLWatermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('increment_field', models.CharField(help_text='用于增量抽取的字段名', max_length=64, verbose_name='增量字段')),
                ('increment_type', models.CharField(choices=[('timestamp', '时间戳'), ('id', '自增ID'), ('cdc', '变更数据')], default='timestamp', help_text='增量策略类型', max_length=20, verbose_name='增量类型')),
                ('watermark_value', models.CharField(help_text='当前水印值（上次抽取的最大值）', max_length=255, verbose_name='水印值')),
                ('execution_id', models.CharField(blank=True, help_text='关联的执行ID', max_length=64, null=True, verbose_name='执行ID')),
                ('task', models.ForeignKey(help_text='关联的ETL任务', on_delete=django.db.models.deletion.CASCADE, related_name='watermarks', to='dataetl.etltask', verbose_name='ETL任务')),
            ],
            options={
                'verbose_name': 'ETL水印',
                'verbose_name_plural': 'ETL水印',
                'db_table': 'dataetl_watermark',
                'ordering': ['-update_time'],
            },
        ),
    ]
