# Generated by Django 5.2.8 on 2026-01-21 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataetl', '0003_alter_integrationtask_type'),
        ('datasource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLineage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('lineage_type', models.CharField(choices=[('table', '表级血缘'), ('field', '字段级血缘')], max_length=10, verbose_name='血缘类型')),
                ('source_table', models.CharField(max_length=256, verbose_name='源表')),
                ('source_field', models.CharField(blank=True, help_text='字段级血缘时必填', max_length=256, verbose_name='源字段')),
                ('target_table', models.CharField(max_length=256, verbose_name='目标表')),
                ('target_field', models.CharField(blank=True, help_text='字段级血缘时必填', max_length=256, verbose_name='目标字段')),
                ('transform_rule', models.TextField(blank=True, verbose_name='转换规则说明')),
            ],
            options={
                'verbose_name': '数据血缘',
                'verbose_name_plural': '数据血缘',
                'db_table': 'dataetl_lineage',
            },
        ),
        migrations.CreateModel(
            name='IntegrationTaskVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('version', models.CharField(help_text='如: v1.0.0', max_length=20, verbose_name='版本号')),
                ('config_snapshot', models.JSONField(help_text='完整任务配置的JSON快照', verbose_name='配置快照')),
                ('change_log', models.TextField(verbose_name='变更日志')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否当前激活版本')),
            ],
            options={
                'verbose_name': 'ETL任务版本',
                'verbose_name_plural': 'ETL任务版本',
                'db_table': 'dataetl_task_version',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='MultiTenantAggregationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('deduplication_fields', models.JSONField(default=list, help_text='如: ["user_id", "tenant_id"]', verbose_name='去重字段列表')),
                ('standardization_rules', models.JSONField(blank=True, default=dict, verbose_name='标准化规则')),
            ],
            options={
                'verbose_name': '多租户聚合配置',
                'verbose_name_plural': '多租户聚合配置',
                'db_table': 'dataetl_multitenant_agg',
            },
        ),
        migrations.CreateModel(
            name='TaskExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('execution_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='执行ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='耗时(秒)')),
                ('rows_read', models.BigIntegerField(default=0, verbose_name='读取行数')),
                ('rows_written', models.BigIntegerField(default=0, verbose_name='写入行数')),
                ('rows_error', models.BigIntegerField(default=0, verbose_name='错误行数')),
                ('bytes_transferred', models.BigIntegerField(default=0, verbose_name='传输字节数')),
                ('log_path', models.CharField(blank=True, default='', max_length=512, verbose_name='日志文件路径')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('stack_trace', models.TextField(blank=True, verbose_name='错误堆栈')),
                ('execution_params', models.JSONField(default=dict, verbose_name='执行参数')),
                ('triggered_by', models.CharField(blank=True, max_length=64, verbose_name='触发方式')),
            ],
            options={
                'verbose_name': '任务执行日志',
                'verbose_name_plural': '任务执行日志',
                'db_table': 'dataetl_execution_log',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddField(
            model_name='integrationtask',
            name='batch_size',
            field=models.IntegerField(default=10000, verbose_name='批处理大小'),
        ),
        migrations.AddField(
            model_name='integrationtask',
            name='concurrency',
            field=models.IntegerField(default=1, verbose_name='并发度'),
        ),
        migrations.AddField(
            model_name='integrationtask',
            name='datax_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='DataX配置扩展'),
        ),
        migrations.AddField(
            model_name='integrationtask',
            name='executor_type',
            field=models.CharField(choices=[('datax', 'DataX执行器'), ('spark_sql', 'Spark SQL执行器'), ('python', 'Python脚本')], default='datax', max_length=20, verbose_name='执行器类型'),
        ),
        migrations.AddField(
            model_name='integrationtask',
            name='field_mapping',
            field=models.JSONField(blank=True, default=list, help_text='[{"source":"id","target":"user_id","type":"int"}]', verbose_name='字段映射'),
        ),
        migrations.AddField(
            model_name='integrationtask',
            name='incremental_field',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='增量字段'),
        ),
        migrations.AddField(
            model_name='integrationtask',
            name='incremental_strategy',
            field=models.CharField(choices=[('full', '全量'), ('incremental_addtime', '按新增时间'), ('incremental_updatetime', '按更新时间'), ('incremental_id', '按自增ID')], default='full', max_length=30, verbose_name='增量策略'),
        ),
        migrations.AddField(
            model_name='integrationtask',
            name='is_multi_db_task',
            field=models.BooleanField(default=False, help_text='同一数据源下的多个租户库合并采集', verbose_name='是否多库采集任务'),
        ),
        migrations.AddField(
            model_name='integrationtask',
            name='post_sql',
            field=models.TextField(blank=True, default='', verbose_name='执行后SQL'),
        ),
        migrations.AddField(
            model_name='integrationtask',
            name='pre_sql',
            field=models.TextField(blank=True, default='', verbose_name='执行前SQL'),
        ),
        migrations.AddField(
            model_name='integrationtask',
            name='source_databases',
            field=models.JSONField(blank=True, default=list, help_text='多库采集时使用，如: ["tenant_db_001", "tenant_db_002"]', verbose_name='源数据库列表'),
        ),
        migrations.AddField(
            model_name='integrationtask',
            name='source_datasource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etl_source_tasks', to='datasource.datasource', verbose_name='源数据源'),
        ),
        migrations.AddField(
            model_name='integrationtask',
            name='source_filter',
            field=models.TextField(blank=True, default='', help_text='WHERE条件，如: update_time > "2026-01-01"', verbose_name='源表过滤条件'),
        ),
        migrations.AddField(
            model_name='integrationtask',
            name='source_table',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='源表名'),
        ),
        migrations.AddField(
            model_name='integrationtask',
            name='target_datasource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etl_target_tasks', to='datasource.datasource', verbose_name='目标数据源'),
        ),
        migrations.AddField(
            model_name='integrationtask',
            name='target_layer',
            field=models.CharField(blank=True, choices=[('stg', 'STG缓冲层'), ('ods', 'ODS原始层'), ('dwd', 'DWD明细层'), ('dws', 'DWS汇总层'), ('ads', 'ADS应用层')], default='', help_text='数据仓库层级', max_length=10, verbose_name='目标层级'),
        ),
        migrations.AddField(
            model_name='integrationtask',
            name='target_partition',
            field=models.JSONField(blank=True, default=dict, help_text='如: {"type": "date", "field": "ds", "format": "yyyyMMdd"}', verbose_name='分区配置'),
        ),
        migrations.AddField(
            model_name='integrationtask',
            name='target_table',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='目标表名'),
        ),
        migrations.AddField(
            model_name='integrationtask',
            name='tenant_id_field',
            field=models.CharField(blank=True, default='', help_text='用于标识租户的字段名，为空则从数据库名提取', max_length=128, verbose_name='租户ID字段'),
        ),
        migrations.AddIndex(
            model_name='integrationtask',
            index=models.Index(fields=['target_layer'], name='dataintegra_target__52041e_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationtask',
            index=models.Index(fields=['executor_type'], name='dataintegra_executo_dfe167_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationtask',
            index=models.Index(fields=['source_datasource'], name='dataintegra_source__e988e9_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationtask',
            index=models.Index(fields=['target_datasource'], name='dataintegra_target__6e979c_idx'),
        ),
        migrations.AddField(
            model_name='datalineage',
            name='source_datasource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineage_sources', to='datasource.datasource', verbose_name='源数据源'),
        ),
        migrations.AddField(
            model_name='datalineage',
            name='source_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineage_outputs', to='dataetl.integrationtask', verbose_name='源任务'),
        ),
        migrations.AddField(
            model_name='datalineage',
            name='target_datasource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineage_targets', to='datasource.datasource', verbose_name='目标数据源'),
        ),
        migrations.AddField(
            model_name='integrationtaskversion',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='dataetl.integrationtask', verbose_name='关联任务'),
        ),
        migrations.AddField(
            model_name='multitenantaggregationtask',
            name='ods_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aggregation_config', to='dataetl.integrationtask', verbose_name='ODS聚合任务'),
        ),
        migrations.AddField(
            model_name='multitenantaggregationtask',
            name='stg_tasks',
            field=models.ManyToManyField(related_name='aggregated_by', to='dataetl.integrationtask', verbose_name='STG任务列表'),
        ),
        migrations.AddField(
            model_name='taskexecutionlog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='dataetl.integrationtask', verbose_name='关联任务'),
        ),
        migrations.AddField(
            model_name='taskexecutionlog',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataetl.integrationtaskversion', verbose_name='任务版本'),
        ),
        migrations.AddIndex(
            model_name='datalineage',
            index=models.Index(fields=['source_datasource', 'source_table'], name='dataintegra_source__0fe4d6_idx'),
        ),
        migrations.AddIndex(
            model_name='datalineage',
            index=models.Index(fields=['target_datasource', 'target_table'], name='dataintegra_target__647180_idx'),
        ),
        migrations.AddIndex(
            model_name='datalineage',
            index=models.Index(fields=['del_flag'], name='dataintegra_del_fla_cb15ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datalineage',
            unique_together={('source_task', 'lineage_type', 'source_table', 'target_table')},
        ),
        migrations.AddIndex(
            model_name='integrationtaskversion',
            index=models.Index(fields=['task', 'version'], name='dataintegra_task_id_18b941_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationtaskversion',
            index=models.Index(fields=['is_active'], name='dataintegra_is_acti_5115bc_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationtaskversion',
            index=models.Index(fields=['del_flag'], name='dataintegra_del_fla_eeb361_idx'),
        ),
        migrations.AddIndex(
            model_name='multitenantaggregationtask',
            index=models.Index(fields=['del_flag'], name='dataintegra_del_fla_58280b_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecutionlog',
            index=models.Index(fields=['task', '-create_time'], name='dataintegra_task_id_e04a41_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecutionlog',
            index=models.Index(fields=['status'], name='dataintegra_status_ca4d5e_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecutionlog',
            index=models.Index(fields=['execution_id'], name='dataintegra_executi_f86446_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecutionlog',
            index=models.Index(fields=['del_flag'], name='dataintegra_del_fla_f9f289_idx'),
        ),
    ]
