# Generated by Django 5.2.8 on 2026-01-21 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0001_initial'),
        ('dataetl', '0004_datalineage_integrationtaskversion_and_more'),
    ]

    operations = [
        # 创建新的ETL任务表
        migrations.CreateModel(
            name='ETLTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_by', models.CharField(max_length=64, null=True, verbose_name='创建者')),
                ('update_by', models.CharField(max_length=64, null=True, verbose_name='更新者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('del_flag', models.CharField(default='0', max_length=1, verbose_name='删除标志')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='任务名称')),
                ('scenario', models.CharField(choices=[('biz_to_stg', '业务库 → STG层'), ('stg_to_ods', 'STG层 → ODS层'), ('warehouse_transform', '数仓层计算转换'), ('warehouse_to_biz', '数仓层 → 业务库'), ('db_to_db', '数据库互相同步')], max_length=30, verbose_name='场景类型', help_text='决定任务的默认配置和执行方式')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '停用')], default='0', max_length=1, verbose_name='状态')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('source_table', models.CharField(blank=True, default='', max_length=255, verbose_name='源表名')),
                ('source_database', models.CharField(blank=True, default='', help_text='某些数据源需要指定数据库', max_length=128, verbose_name='源数据库名')),
                ('source_filter', models.TextField(blank=True, default='', help_text='WHERE条件，如: status = 1', verbose_name='过滤条件')),
                ('target_table', models.CharField(blank=True, default='', max_length=255, verbose_name='目标表名')),
                ('target_database', models.CharField(blank=True, default='', help_text='目标数据库名或schema', max_length=128, verbose_name='目标数据库名')),
                ('target_layer', models.CharField(blank=True, default='', help_text='数仓层级: stg/ods/dwd/dws/ads', max_length=10, verbose_name='目标层级')),
                ('sync_mode', models.CharField(choices=[('full', '全量同步'), ('incremental', '增量同步')], default='full', max_length=20, verbose_name='同步方式')),
                ('incremental_field', models.CharField(blank=True, default='', help_text='增量同步时使用的时间戳或ID字段', max_length=128, verbose_name='增量字段')),
                ('field_mappings', models.JSONField(blank=True, default=list, help_text='格式: [{"source": "id", "target": "user_id"}]', verbose_name='字段映射')),
                ('sql_script', models.TextField(blank=True, default='', help_text='Spark SQL脚本，用于数仓计算场景', verbose_name='SQL脚本')),
                ('transform_rules', models.TextField(blank=True, default='', help_text='数据清洗和转换规则', verbose_name='转换规则')),
                ('executor_type', models.CharField(choices=[('datax', 'DataX执行器'), ('spark_sql', 'Spark SQL执行器')], default='datax', max_length=20, verbose_name='执行器类型')),
                ('batch_size', models.IntegerField(default=10000, verbose_name='批处理大小')),
                ('concurrency', models.IntegerField(default=1, verbose_name='并发数')),
                ('schedule_type', models.CharField(choices=[('manual', '手动执行'), ('scheduled', '定时执行')], default='manual', max_length=20, verbose_name='执行方式')),
                ('schedule_cron', models.CharField(blank=True, default='', help_text='定时执行的cron表达式', max_length=100, verbose_name='Cron表达式')),
                ('advanced_config', models.JSONField(blank=True, default=dict, help_text='存储扩展配置，如分区信息、写入模式等', verbose_name='高级配置')),
                ('source_datasource', models.ForeignKey(blank=True, help_text='源数据源ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etl_source_tasks', to='datasource.datasource', verbose_name='源数据源')),
                ('target_datasource', models.ForeignKey(blank=True, help_text='目标数据源ID，为空表示Hive', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etl_target_tasks', to='datasource.datasource', verbose_name='目标数据源')),
            ],
            options={
                'verbose_name': 'ETL任务',
                'verbose_name_plural': 'ETL任务',
                'db_table': 'etl_task',
                'indexes': [
                    models.Index(fields=['scenario'], name='etl_task_scenario_idx'),
                    models.Index(fields=['status'], name='etl_task_status_idx'),
                    models.Index(fields=['schedule_type'], name='etl_task_schedule_type_idx'),
                    models.Index(fields=['-create_time'], name='etl_task_create_time_idx'),
                ],
            },
        ),
        # 创建新的ETL执行记录表
        migrations.CreateModel(
            name='ETLExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_by', models.CharField(max_length=64, null=True, verbose_name='创建者')),
                ('update_by', models.CharField(max_length=64, null=True, verbose_name='更新者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('del_flag', models.CharField(default='0', max_length=1, verbose_name='删除标志')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('rows_read', models.BigIntegerField(default=0, verbose_name='读取行数')),
                ('rows_written', models.BigIntegerField(default=0, verbose_name='写入行数')),
                ('rows_failed', models.IntegerField(default=0, verbose_name='失败行数')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.IntegerField(default=0, verbose_name='执行时长(秒)')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('current_stage', models.CharField(blank=True, default='', max_length=255, verbose_name='当前阶段')),
                ('logs', models.JSONField(blank=True, default=list, verbose_name='执行日志')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('execution_snapshot', models.JSONField(blank=True, default=dict, verbose_name='执行参数快照')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='dataetl.etltask', verbose_name='任务')),
            ],
            options={
                'verbose_name': 'ETL执行记录',
                'verbose_name_plural': 'ETL执行记录',
                'db_table': 'etl_execution',
                'ordering': ['-create_time'],
                'indexes': [
                    models.Index(fields=['task', '-create_time'], name='etl_exec_task_time_idx'),
                    models.Index(fields=['status'], name='etl_exec_status_idx'),
                    models.Index(fields=['-create_time'], name='etl_exec_create_time_idx'),
                ],
            },
        ),
        # 创建新的ETL模板表
        migrations.CreateModel(
            name='ETLTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_by', models.CharField(max_length=64, null=True, verbose_name='创建者')),
                ('update_by', models.CharField(max_length=64, null=True, verbose_name='更新者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('del_flag', models.CharField(default='0', max_length=1, verbose_name='删除标志')),
                ('scenario', models.CharField(choices=[('biz_to_stg', '业务库 → STG层'), ('stg_to_ods', 'STG层 → ODS层'), ('warehouse_transform', '数仓层计算转换'), ('warehouse_to_biz', '数仓层 → 业务库'), ('db_to_db', '数据库互相同步')], max_length=30, verbose_name='场景类型')),
                ('name', models.CharField(max_length=255, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='模板描述')),
                ('template_config', models.JSONField(help_text='存储任务配置的JSON', verbose_name='模板配置')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('is_system', models.BooleanField(default=False, help_text='系统预设的模板', verbose_name='系统模板')),
            ],
            options={
                'verbose_name': 'ETL模板',
                'verbose_name_plural': 'ETL模板',
                'db_table': 'etl_template',
                'indexes': [
                    models.Index(fields=['scenario'], name='etl_tpl_scenario_idx'),
                    models.Index(fields=['is_system'], name='etl_tpl_is_system_idx'),
                ],
            },
        ),
    ]
