# Generated by Django 5.2.8 on 2026-01-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataetl', '0005_auto_20260121_1542'),
    ]

    operations = [
    ]
