# Generated by Django 5.2.8 on 2026-01-23 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataetl', '0006_auto_20260121_1621'),
        ('datataskmonitor', '0003_taskexecution_taskexecutionlog'),
    ]

    operations = [
        # Add execution_mode field to ETLTask
        migrations.AddField(
            model_name='etltask',
            name='execution_mode',
            field=models.CharField(
                choices=[('manual', '手动执行'), ('scheduled', '定时执行')],
                default='manual',
                help_text='手动执行或定时执行',
                max_length=20,
                verbose_name='执行方式'
            ),
        ),
        # Create ETLTaskDependency model first
        migrations.CreateModel(
            name='ETLTaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('predecessor', models.ForeignKey(
                    help_text='需要先完成的任务',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='dependency_successors',
                    to='etltask',
                    verbose_name='前置任务'
                )),
                ('successor', models.ForeignKey(
                    help_text='依赖前置任务的任务',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='dependency_predecessors',
                    to='etltask',
                    verbose_name='后置任务'
                )),
            ],
            options={
                'verbose_name': 'ETL任务依赖',
                'verbose_name_plural': 'ETL任务依赖',
                'db_table': 'etl_task_dependency',
                'indexes': [
                    models.Index(fields=['predecessor'], name='etl_task_dep_predecessor_idx'),
                    models.Index(fields=['successor'], name='etl_task_dep_successor_idx'),
                ],
            },
        ),
        # Add depends_on_tasks ManyToManyField to ETLTask
        migrations.AddField(
            model_name='etltask',
            name='depends_on_tasks',
            field=models.ManyToManyField(
                blank=True,
                help_text='此任务依赖的其他任务（必须先完成依赖任务才能执行此任务）',
                related_name='dependent_tasks',
                through='ETLTaskDependency',
                to='etltask',
            ),
        ),
        # Add execution OneToOneField to ETLExecution (nullable for migration)
        migrations.AddField(
            model_name='etlexecution',
            name='execution',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='etl_details',
                to='datataskmonitor.taskexecution',
                verbose_name='通用执行记录'
            ),
        ),
    ]
