# Generated by Django 5.2.8 on 2025-12-23 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('rule_name', models.CharField(max_length=128, verbose_name='规则名称')),
                ('rule_type', models.CharField(choices=[('failure', '任务失败'), ('timeout', '运行超时')], max_length=20, verbose_name='规则类型')),
                ('threshold', models.IntegerField(default=0, help_text='超时时间(秒)或重试次数', verbose_name='阈值')),
                ('notification_channels', models.CharField(help_text='逗号分隔', max_length=128, verbose_name='通知渠道')),
                ('receivers', models.TextField(help_text='逗号分隔', verbose_name='接收人')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '报警规则',
                'verbose_name_plural': '报警规则',
                'db_table': 'dt_alert_rule',
            },
        ),
        migrations.CreateModel(
            name='DataTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('task_name', models.CharField(max_length=128, verbose_name='任务名称')),
                ('task_type', models.CharField(choices=[('collection', '数据采集'), ('sync', '数据同步'), ('calculation', '数据计算'), ('storage', '数据存储')], max_length=20, verbose_name='任务类型')),
                ('schedule_type', models.CharField(choices=[('cron', 'Cron表达式'), ('interval', '固定间隔'), ('once', '单次执行')], default='cron', max_length=20, verbose_name='调度类型')),
                ('schedule_conf', models.CharField(help_text='Cron表达式或间隔时间(秒)', max_length=256, verbose_name='调度配置')),
                ('status', models.CharField(choices=[('running', '运行中'), ('paused', '暂停'), ('failed', '失败'), ('success', '成功'), ('idle', '空闲')], default='idle', max_length=20, verbose_name='任务状态')),
                ('last_run_time', models.DateTimeField(blank=True, null=True, verbose_name='上次运行时间')),
                ('next_run_time', models.DateTimeField(blank=True, null=True, verbose_name='下次运行时间')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '数据任务',
                'verbose_name_plural': '数据任务',
                'db_table': 'dt_task',
            },
        ),
        migrations.CreateModel(
            name='AlertRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('task_name', models.CharField(max_length=128, verbose_name='相关任务')),
                ('trigger_time', models.DateTimeField(auto_now_add=True, verbose_name='触发时间')),
                ('content', models.TextField(verbose_name='报警内容')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('handled', '已处理'), ('ignored', '已忽略')], default='pending', max_length=20, verbose_name='处理状态')),
                ('handle_time', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('handle_note', models.TextField(blank=True, verbose_name='处理备注')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datataskmonitor.alertrule', verbose_name='触发规则')),
            ],
            options={
                'verbose_name': '报警记录',
                'verbose_name_plural': '报警记录',
                'db_table': 'dt_alert_record',
                'ordering': ['-trigger_time'],
            },
        ),
        migrations.AddField(
            model_name='alertrule',
            name='task',
            field=models.ForeignKey(blank=True, help_text='为空则为全局规则', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='datataskmonitor.datatask', verbose_name='关联任务'),
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('status', models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('failed', '失败')], max_length=20, verbose_name='运行状态')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('message', models.TextField(blank=True, verbose_name='日志信息')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='datataskmonitor.datatask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '任务日志',
                'verbose_name_plural': '任务日志',
                'db_table': 'dt_task_log',
                'ordering': ['-create_time'],
            },
        ),
    ]
