# Generated by Django 5.2.8 on 2025-12-26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datastudio', '0001_initial'),
        ('datataskmonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatask',
            name='enabled',
            field=models.CharField(choices=[('0', '启用'), ('1', '禁用')], default='0', max_length=1, verbose_name='启用状态'),
        ),
        migrations.AddField(
            model_name='datatask',
            name='source_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ops_task', to='datastudio.datastudiotask', verbose_name='来源任务'),
        ),
    ]

