# Generated by Django 5.2.8 on 2026-01-23 15:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datataskmonitor', '0002_link_datastudio_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('task_type', models.CharField(choices=[('etl', 'ETL任务'), ('metadata_collection', '元数据采集'), ('quality_check', '质量检查'), ('data_sync', '数据同步'), ('calculation', '数据计算')], db_index=True, max_length=30, verbose_name='任务类型')),
                ('task_id', models.IntegerField(db_index=True, help_text='实际任务的ID（如ETLTask.id、MetaCollectionTask.id等）', verbose_name='任务ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration_seconds', models.IntegerField(blank=True, help_text='自动计算：end_time - start_time', null=True, verbose_name='执行时长(秒)')),
                ('status', models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='running', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, help_text='0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='进度百分比')),
                ('rows_read', models.BigIntegerField(blank=True, null=True, verbose_name='读取行数')),
                ('rows_written', models.BigIntegerField(blank=True, null=True, verbose_name='写入行数')),
                ('bytes_processed', models.BigIntegerField(blank=True, null=True, verbose_name='处理字节数')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('error_stack', models.TextField(blank=True, default='', verbose_name='错误堆栈')),
                ('peak_memory_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='峰值内存(MB)')),
                ('log_file_path', models.CharField(blank=True, default='', max_length=512, verbose_name='日志文件路径')),
                ('executor_type', models.CharField(blank=True, default='', help_text='如: datax, spark_sql', max_length=50, verbose_name='执行器类型')),
                ('execution_params', models.JSONField(blank=True, default=dict, help_text='执行时的任务配置快照', verbose_name='执行参数快照')),
            ],
            options={
                'verbose_name': '任务执行记录',
                'verbose_name_plural': '任务执行记录',
                'db_table': 'task_execution',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['task_type', 'task_id', '-start_time'], name='task_execut_task_ty_02555d_idx'), models.Index(fields=['status', '-start_time'], name='task_execut_status_efebc3_idx'), models.Index(fields=['-start_time'], name='task_execut_start_t_74674d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('log_level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR')], db_index=True, default='INFO', max_length=10, verbose_name='日志级别')),
                ('message', models.TextField(verbose_name='日志消息')),
                ('metadata', models.JSONField(blank=True, help_text='额外的上下文信息', null=True, verbose_name='元数据')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='datataskmonitor.taskexecution', verbose_name='执行记录')),
            ],
            options={
                'verbose_name': '任务执行日志',
                'verbose_name_plural': '任务执行日志',
                'db_table': 'task_execution_log',
                'ordering': ['create_time'],
                'indexes': [models.Index(fields=['execution', 'create_time'], name='task_execut_executi_877d94_idx'), models.Index(fields=['execution', 'log_level'], name='task_execut_executi_4bbe6a_idx')],
            },
        ),
    ]
