# Generated by Django 5.2.8 on 2026-05-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_logininfor'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='operlog',
            new_name='monitor_ope_del_fla_3b99c2_idx',
            old_name='sys_oper_lo_del_fla_79e0f0_idx',
        ),
        migrations.RenameIndex(
            model_name='operlog',
            new_name='monitor_ope_status_e8760f_idx',
            old_name='sys_oper_lo_status_53f496_idx',
        ),
        migrations.RenameIndex(
            model_name='operlog',
            new_name='monitor_ope_oper_ti_4fb6e3_idx',
            old_name='sys_oper_lo_oper_ti_62325b_idx',
        ),
        migrations.RenameIndex(
            model_name='operlog',
            new_name='monitor_ope_oper_na_2c5e04_idx',
            old_name='sys_oper_lo_oper_na_9ab872_idx',
        ),
        migrations.RenameIndex(
            model_name='operlog',
            new_name='monitor_ope_title_a9e838_idx',
            old_name='sys_oper_lo_title_2a8802_idx',
        ),
        migrations.RenameIndex(
            model_name='operlog',
            new_name='monitor_ope_busines_da3ccd_idx',
            old_name='sys_oper_lo_busines_d2a9e7_idx',
        ),
        migrations.AlterModelTable(
            name='logininfor',
            table='monitor_login_info',
        ),
        migrations.AlterModelTable(
            name='operlog',
            table='monitor_oper_log',
        ),
    ]
