# Generated by Django 5.2.8 on 2025-12-04 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasource', '0003_delete_querylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('report_id', models.IntegerField(blank=True, null=True, verbose_name='报表ID')),
                ('interface_name', models.CharField(max_length=255, verbose_name='接口名称')),
                ('interface_code', models.CharField(max_length=255, unique=True, verbose_name='接口编码')),
                ('interface_desc', models.TextField(blank=True, null=True, verbose_name='接口描述')),
                ('interface_db_type', models.CharField(max_length=255, verbose_name='数据库类型')),
                ('interface_db_name', models.CharField(max_length=255, verbose_name='数据库名称')),
                ('interface_sql', models.TextField(blank=True, null=True, verbose_name='接口sql')),
                ('is_total', models.CharField(choices=[('1', '是'), ('0', '否')], default='0', max_length=1, verbose_name='是否合计')),
                ('total_sql', models.TextField(blank=True, null=True, verbose_name='合计sql')),
                ('is_paging', models.CharField(choices=[('1', '是'), ('0', '否')], default='0', max_length=1, verbose_name='是否分页')),
                ('is_date_option', models.CharField(choices=[('1', '是'), ('0', '否')], default='0', max_length=1, verbose_name='是否日期查询')),
                ('is_second_table', models.CharField(choices=[('1', '是'), ('0', '否')], default='0', max_length=1, verbose_name='二级表头')),
                ('is_login_visit', models.CharField(choices=[('1', '是'), ('0', '否')], default='0', max_length=1, verbose_name='是否登陆验证')),
                ('alarm_type', models.CharField(choices=[('0', '否'), ('1', '邮件'), ('2', '短信'), ('3', '钉钉'), ('4', '企业微信'), ('5', '电话'), ('6', '飞书')], default='0', max_length=1, verbose_name='报警类型')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户名称')),
                ('interface_datasource', models.IntegerField(blank=True, null=True, verbose_name='数据源ID')),
            ],
            options={
                'verbose_name': '数据接口信息',
                'verbose_name_plural': '数据接口信息',
                'db_table': 'dataservice_interface_info',
                'indexes': [models.Index(fields=['interface_code'], name='dataservice_interfa_4a8568_idx'), models.Index(fields=['del_flag'], name='dataservice_del_fla_c855ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='InterfaceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('interface_para_code', models.CharField(max_length=255, verbose_name='接口参数编码')),
                ('interface_para_name', models.CharField(max_length=255, verbose_name='接口参数名称')),
                ('interface_para_position', models.IntegerField(verbose_name='接口参数位置')),
                ('interface_para_type', models.CharField(choices=[('1', '输入参数'), ('2', '输出参数')], max_length=255, verbose_name='接口参数类型')),
                ('interface_data_type', models.CharField(choices=[('1', '字符'), ('2', '整数'), ('3', '小数'), ('4', '百分比'), ('5', '无格式整数'), ('6', '无格式小数'), ('7', '无格式百分比'), ('8', '1位百分比'), ('9', '1位小数'), ('10', '年份'), ('11', '日期'), ('12', '月份'), ('13', '单选'), ('14', '多选'), ('15', '文本')], max_length=255, verbose_name='接口参数数据类型')),
                ('interface_para_default', models.CharField(blank=True, max_length=255, null=True, verbose_name='接口参数默认值')),
                ('interface_para_rowspan', models.IntegerField(blank=True, choices=[(1, '是'), (0, '否')], null=True, verbose_name='接口参数跨行')),
                ('interface_parent_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='接口参数父级名称')),
                ('interface_parent_position', models.IntegerField(blank=True, null=True, verbose_name='接口参数父级位置')),
                ('interface_para_interface_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='接口参数接口编码')),
                ('interface_cascade_para', models.CharField(blank=True, max_length=255, null=True, verbose_name='接口参数级联参数')),
                ('interface_show_flag', models.CharField(choices=[('1', '是'), ('0', '否')], default='1', max_length=255, verbose_name='接口参数是否显示')),
                ('interface_export_flag', models.CharField(choices=[('1', '是'), ('0', '否')], default='1', max_length=255, verbose_name='接口参数是否导出')),
                ('interface_show_desc', models.CharField(blank=True, choices=[('1', '是'), ('0', '否')], max_length=255, null=True, verbose_name='接口参数显示名称')),
                ('interface_para_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='接口参数描述')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataservice.interfaceinfo', verbose_name='接口')),
            ],
            options={
                'verbose_name': '数据接口字段',
                'verbose_name_plural': '数据接口字段',
                'db_table': 'dataservice_interface_field',
                'indexes': [models.Index(fields=['interface'], name='dataservice_interfa_a4f201_idx'), models.Index(fields=['del_flag'], name='dataservice_del_fla_b32811_idx')],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('sql_text', models.TextField(verbose_name='SQL语句')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('status', models.CharField(choices=[('success', '成功'), ('fail', '失败')], default='success', max_length=10, verbose_name='执行状态')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时(ms)')),
                ('error_msg', models.CharField(blank=True, default='', max_length=500, verbose_name='错误信息')),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datasource.datasource', verbose_name='数据源')),
            ],
            options={
                'verbose_name': '数据查询日志',
                'verbose_name_plural': '数据查询日志',
                'db_table': 'datasource_query_log',
                'indexes': [models.Index(fields=['username'], name='datasource__usernam_f69aca_idx'), models.Index(fields=['status'], name='datasource__status_2c1377_idx'), models.Index(fields=['data_source'], name='datasource__data_so_96e741_idx'), models.Index(fields=['del_flag'], name='datasource__del_fla_72c6e9_idx')],
            },
        ),
    ]
