# Generated by Django 5.2.8 on 2025-12-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='query_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='查询类型'),
        ),
    ]
