# Generated by Django 5.2.8 on 2025-12-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservice', '0002_querylog_query_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfaceinfo',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
    ]
