# Generated by Django 5.2.8 on 2025-12-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservice', '0003_interfaceinfo_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaceinfo',
            name='enable',
            field=models.CharField(default='1', verbose_name='是否启用'),
        ),
    ]
