# Generated by Django 5.2.8 on 2025-12-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservice', '0004_alter_interfaceinfo_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaceinfo',
            name='enable',
            field=models.CharField(choices=[('1', '启用'), ('0', '禁用')], default='1', max_length=1, verbose_name='是否启用'),
        ),
    ]
