# Generated by Django 5.2.8 on 2026-01-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservice', '0005_alter_interfaceinfo_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfaceinfo',
            name='module_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='模块名称'),
        ),
        migrations.AddField(
            model_name='interfaceinfo',
            name='platform_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='业务平台'),
        ),
        migrations.AddField(
            model_name='interfaceinfo',
            name='report_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='报表编码'),
        ),
        migrations.AddField(
            model_name='interfaceinfo',
            name='report_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='报表名称'),
        ),
    ]
