# Generated by Django 5.2.8 on 2026-03-24 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservice', '0006_interfaceinfo_module_name_and_more'),
        ('datasource', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='querylog',
                    name='data_source',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datasource.datasource', verbose_name='数据源'),
                ),
            ],
            database_operations=[],
        ),
    ]
