# Generated by Django 5.2.8 on 2026-04-19 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservice', '0007_alter_querylog_data_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('report_name', models.CharField(max_length=255, verbose_name='报表名称')),
                ('report_code', models.CharField(max_length=255, unique=True, verbose_name='报表编码')),
                ('report_desc', models.TextField(blank=True, null=True, verbose_name='报表描述')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '报表信息',
                'verbose_name_plural': '报表信息',
                'db_table': 'dataservice_report_info',
                'indexes': [models.Index(fields=['report_code'], name='dataservice_report__b96917_idx'), models.Index(fields=['del_flag'], name='dataservice_del_fla_9ba4f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportInterfaceRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('interface_position', models.IntegerField(default=1, verbose_name='接口顺序')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_reports', to='dataservice.interfaceinfo', verbose_name='接口')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_interfaces', to='dataservice.reportinfo', verbose_name='报表')),
            ],
            options={
                'verbose_name': '报表接口关联',
                'verbose_name_plural': '报表接口关联',
                'db_table': 'dataservice_report_interface_relation',
                'indexes': [models.Index(fields=['report'], name='dataservice_report__90773a_idx'), models.Index(fields=['interface'], name='dataservice_interfa_d74863_idx'), models.Index(fields=['del_flag'], name='dataservice_del_fla_60bb6c_idx')],
                'constraints': [models.UniqueConstraint(fields=('report', 'interface', 'del_flag'), name='uniq_report_interface_active')],
            },
        ),
    ]
