# Generated by Django 5.2.8 on 2026-02-04 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('name', models.CharField(max_length=64, verbose_name='数据源名称')),
                ('db_type', models.CharField(max_length=20, verbose_name='数据库类型')),
                ('host', models.CharField(blank=True, default='', max_length=128, verbose_name='主机')),
                ('port', models.IntegerField(default=0, verbose_name='端口')),
                ('db_name', models.CharField(blank=True, default='', max_length=128, verbose_name='数据库名')),
                ('username', models.CharField(blank=True, default='', max_length=128, verbose_name='用户名')),
                ('password', models.CharField(blank=True, default='', max_length=256, verbose_name='密码')),
                ('params', models.TextField(blank=True, default='', verbose_name='连接参数(JSON 或 KV)')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '停用')], default='0', max_length=1, verbose_name='状态')),
                ('remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
            ],
            options={
                'verbose_name': '数据源',
                'verbose_name_plural': '数据源',
                'db_table': 'dataasset_datasource',
                'indexes': [models.Index(fields=['name'], name='dataasset_d_name_cc0358_idx'), models.Index(fields=['db_type'], name='dataasset_d_db_type_d0e0ab_idx'), models.Index(fields=['status'], name='dataasset_d_status_9cdf07_idx'), models.Index(fields=['del_flag'], name='dataasset_d_del_fla_891397_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetaTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('table_name', models.CharField(max_length=256, verbose_name='表名')),
                ('comment', models.CharField(blank=True, default='', max_length=1024, verbose_name='表注释')),
                ('database', models.CharField(blank=True, default='', max_length=256, verbose_name='数据库名')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_tables', to='dataasset.datasource')),
            ],
            options={
                'verbose_name': '元数据表',
                'verbose_name_plural': '元数据表',
                'db_table': 'dataasset_meta_table',
            },
        ),
        migrations.CreateModel(
            name='MetaColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('order', models.IntegerField(default=0, verbose_name='字段顺序')),
                ('name', models.CharField(max_length=256, verbose_name='字段名')),
                ('type', models.CharField(blank=True, default='', max_length=256, verbose_name='字段类型')),
                ('notnull', models.BooleanField(default=False, verbose_name='是否可空')),
                ('default', models.CharField(blank=True, default='', max_length=512, verbose_name='默认值')),
                ('primary', models.BooleanField(default=False, verbose_name='是否主键')),
                ('comment', models.CharField(blank=True, default='', max_length=1024, verbose_name='字段注释')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_columns', to='dataasset.datasource')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='dataasset.metatable')),
            ],
            options={
                'verbose_name': '元数据字段',
                'verbose_name_plural': '元数据字段',
                'db_table': 'dataasset_meta_column',
            },
        ),
        migrations.CreateModel(
            name='TableLineage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('lineage_type', models.CharField(choices=[('upstream', '上游'), ('downstream', '下游')], default='upstream', max_length=20, verbose_name='血缘类型')),
                ('description', models.CharField(blank=True, default='', max_length=1024, verbose_name='描述')),
                ('source_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downstream_lineages', to='dataasset.metatable', verbose_name='源表')),
                ('target_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_lineages', to='dataasset.metatable', verbose_name='目标表')),
            ],
            options={
                'verbose_name': '表血缘关系',
                'verbose_name_plural': '表血缘关系',
                'db_table': 'dataasset_table_lineage',
            },
        ),
        migrations.CreateModel(
            name='MetaCollectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('task_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='任务ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '采集中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('current_table', models.CharField(blank=True, max_length=256, verbose_name='当前处理表')),
                ('total_tables', models.IntegerField(default=0, verbose_name='总表数')),
                ('collected_tables', models.IntegerField(default=0, verbose_name='已采集表数')),
                ('failed_tables', models.IntegerField(default=0, verbose_name='失败表数')),
                ('database_name', models.CharField(blank=True, max_length=256, verbose_name='数据库名')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('thread_id', models.CharField(blank=True, max_length=64, verbose_name='线程ID')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_tasks', to='dataasset.datasource')),
            ],
            options={
                'verbose_name': '元数据采集任务',
                'verbose_name_plural': '元数据采集任务',
                'db_table': 'dataasset_collection_task',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['status'], name='dataasset_c_status_a37e4f_idx'), models.Index(fields=['data_source', 'create_time'], name='dataasset_c_data_so_259ccb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='metatable',
            index=models.Index(fields=['del_flag'], name='dataasset_m_del_fla_7b4261_idx'),
        ),
        migrations.AddIndex(
            model_name='metatable',
            index=models.Index(fields=['data_source', 'table_name'], name='dataasset_m_data_so_1d0e1a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='metatable',
            unique_together={('data_source', 'table_name', 'database')},
        ),
        migrations.AddIndex(
            model_name='metacolumn',
            index=models.Index(fields=['del_flag'], name='dataasset_m_del_fla_f3a96f_idx'),
        ),
        migrations.AddIndex(
            model_name='metacolumn',
            index=models.Index(fields=['table', 'order'], name='dataasset_m_table_i_e1f798_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='metacolumn',
            unique_together={('data_source', 'table', 'name')},
        ),
        migrations.AddIndex(
            model_name='tablelineage',
            index=models.Index(fields=['del_flag'], name='dataasset_t_del_fla_a69567_idx'),
        ),
        migrations.AddIndex(
            model_name='tablelineage',
            index=models.Index(fields=['source_table', 'target_table'], name='dataasset_t_source__271306_idx'),
        ),
        migrations.AddIndex(
            model_name='tablelineage',
            index=models.Index(fields=['lineage_type'], name='dataasset_t_lineage_25793b_idx'),
        ),
        migrations.AddConstraint(
            model_name='tablelineage',
            constraint=models.CheckConstraint(condition=models.Q(('source_table', models.F('target_table')), _negated=True), name='source_target_not_same'),
        ),
    ]
