# Generated by Django 5.2.8 on 2026-04-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataasset', '0005_metacollectiontask_active_task_constraint'),
        ('datasource', '0003_datasource_connectivity_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataasset',
            name='asset_category',
            field=models.CharField(choices=[('source', '源端元数据'), ('business', '业务元数据'), ('warehouse', '数仓元数据'), ('service', '服务资产'), ('other', '其他资产')], default='source', max_length=32, verbose_name='资产分类'),
        ),
        migrations.AddField(
            model_name='dataasset',
            name='business_domain',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='业务域'),
        ),
        migrations.AddField(
            model_name='dataasset',
            name='grain',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='数据粒度'),
        ),
        migrations.AddField(
            model_name='dataasset',
            name='lifecycle_status',
            field=models.CharField(choices=[('draft', '草稿'), ('active', '在线'), ('offline', '下线'), ('archived', '归档')], default='draft', max_length=16, verbose_name='生命周期状态'),
        ),
        migrations.AddField(
            model_name='dataasset',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='资产负责人'),
        ),
        migrations.AddField(
            model_name='dataasset',
            name='security_level',
            field=models.CharField(choices=[('public', '公开'), ('internal', '内部'), ('sensitive', '敏感'), ('restricted', '严格受限')], default='internal', max_length=16, verbose_name='安全等级'),
        ),
        migrations.AddField(
            model_name='dataasset',
            name='steward',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='数据管家'),
        ),
        migrations.AddField(
            model_name='dataasset',
            name='subject_area',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='主题域'),
        ),
        migrations.AddField(
            model_name='dataasset',
            name='warehouse_layer',
            field=models.CharField(blank=True, choices=[('', '未设置'), ('SOURCE', '源端'), ('ODS', '贴源层'), ('DWD', '明细层'), ('DWS', '汇总层'), ('ADS', '应用层'), ('DIM', '维度层')], default='', max_length=16, verbose_name='数仓分层'),
        ),
        migrations.AddField(
            model_name='dataassetcolumn',
            name='business_term',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='业务术语'),
        ),
        migrations.AddField(
            model_name='dataassetcolumn',
            name='metric_unit',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='指标单位'),
        ),
        migrations.AddField(
            model_name='dataassetcolumn',
            name='security_level',
            field=models.CharField(choices=[('public', '公开'), ('internal', '内部'), ('sensitive', '敏感'), ('restricted', '严格受限')], default='internal', max_length=16, verbose_name='安全等级'),
        ),
        migrations.AddField(
            model_name='dataassetcolumn',
            name='standard_code',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='标准编码'),
        ),
        migrations.AddField(
            model_name='dataassetcolumn',
            name='warehouse_role',
            field=models.CharField(blank=True, choices=[('', '未设置'), ('dimension', '维度字段'), ('measure', '指标字段'), ('partition_key', '分区字段'), ('business_key', '业务主键'), ('attribute', '属性字段')], default='', max_length=32, verbose_name='数仓字段角色'),
        ),
        migrations.AddField(
            model_name='metacolumn',
            name='business_term',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='业务术语'),
        ),
        migrations.AddField(
            model_name='metacolumn',
            name='metric_unit',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='指标单位'),
        ),
        migrations.AddField(
            model_name='metacolumn',
            name='security_level',
            field=models.CharField(choices=[('public', '公开'), ('internal', '内部'), ('sensitive', '敏感'), ('restricted', '严格受限')], default='internal', max_length=16, verbose_name='安全等级'),
        ),
        migrations.AddField(
            model_name='metacolumn',
            name='standard_code',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='标准编码'),
        ),
        migrations.AddField(
            model_name='metacolumn',
            name='warehouse_role',
            field=models.CharField(blank=True, choices=[('', '未设置'), ('dimension', '维度字段'), ('measure', '指标字段'), ('partition_key', '分区字段'), ('business_key', '业务主键'), ('attribute', '属性字段')], default='', max_length=32, verbose_name='数仓字段角色'),
        ),
        migrations.AddField(
            model_name='metatable',
            name='asset_category',
            field=models.CharField(choices=[('source', '源端元数据'), ('business', '业务元数据'), ('warehouse', '数仓元数据'), ('service', '服务资产'), ('other', '其他资产')], default='source', max_length=32, verbose_name='资产分类'),
        ),
        migrations.AddField(
            model_name='metatable',
            name='business_domain',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='业务域'),
        ),
        migrations.AddField(
            model_name='metatable',
            name='grain',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='数据粒度'),
        ),
        migrations.AddField(
            model_name='metatable',
            name='lifecycle_status',
            field=models.CharField(choices=[('draft', '草稿'), ('active', '在线'), ('offline', '下线'), ('archived', '归档')], default='draft', max_length=16, verbose_name='生命周期状态'),
        ),
        migrations.AddField(
            model_name='metatable',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='资产负责人'),
        ),
        migrations.AddField(
            model_name='metatable',
            name='security_level',
            field=models.CharField(choices=[('public', '公开'), ('internal', '内部'), ('sensitive', '敏感'), ('restricted', '严格受限')], default='internal', max_length=16, verbose_name='安全等级'),
        ),
        migrations.AddField(
            model_name='metatable',
            name='steward',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='数据管家'),
        ),
        migrations.AddField(
            model_name='metatable',
            name='subject_area',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='主题域'),
        ),
        migrations.AddField(
            model_name='metatable',
            name='warehouse_layer',
            field=models.CharField(blank=True, choices=[('', '未设置'), ('SOURCE', '源端'), ('ODS', '贴源层'), ('DWD', '明细层'), ('DWS', '汇总层'), ('ADS', '应用层'), ('DIM', '维度层')], default='', max_length=16, verbose_name='数仓分层'),
        ),
        migrations.AddIndex(
            model_name='dataasset',
            index=models.Index(fields=['asset_category'], name='dataasset_d_asset_c_01911a_idx'),
        ),
        migrations.AddIndex(
            model_name='dataasset',
            index=models.Index(fields=['warehouse_layer'], name='dataasset_d_warehou_ec71b0_idx'),
        ),
        migrations.AddIndex(
            model_name='dataasset',
            index=models.Index(fields=['owner'], name='dataasset_d_owner_8f1642_idx'),
        ),
        migrations.AddIndex(
            model_name='dataassetcolumn',
            index=models.Index(fields=['security_level'], name='dataasset_d_securit_39a37b_idx'),
        ),
        migrations.AddIndex(
            model_name='metacolumn',
            index=models.Index(fields=['security_level'], name='dataasset_m_securit_583b62_idx'),
        ),
        migrations.AddIndex(
            model_name='metatable',
            index=models.Index(fields=['asset_category'], name='dataasset_m_asset_c_77ab56_idx'),
        ),
        migrations.AddIndex(
            model_name='metatable',
            index=models.Index(fields=['warehouse_layer'], name='dataasset_m_warehou_9eb78a_idx'),
        ),
        migrations.AddIndex(
            model_name='metatable',
            index=models.Index(fields=['owner'], name='dataasset_m_owner_0545f9_idx'),
        ),
    ]
