# Generated by Django 5.2.8 on 2026-04-05 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDevScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('script_name', models.CharField(max_length=128, verbose_name='脚本名称')),
                ('script_code', models.CharField(max_length=64, unique=True, verbose_name='脚本编码')),
                ('script_type', models.CharField(choices=[('sql', 'SQL'), ('python', 'Python')], default='sql', max_length=20, verbose_name='脚本类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='脚本描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('owner', models.CharField(blank=True, default='', max_length=64, verbose_name='归属人')),
                ('project_id', models.CharField(blank=True, default='', max_length=64, verbose_name='项目ID')),
                ('datasource', models.ForeignKey(blank=True, help_text='SQL 脚本执行时使用的数据源', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_scripts', to='datasource.datasource', verbose_name='关联数据源')),
            ],
            options={
                'verbose_name': '数据开发脚本',
                'verbose_name_plural': '数据开发脚本',
                'db_table': 'datadev_script',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='DataDevScriptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='版本号')),
                ('content', models.TextField(verbose_name='脚本内容')),
                ('content_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='内容哈希')),
                ('change_log', models.TextField(blank=True, default='', verbose_name='变更说明')),
                ('is_current', models.BooleanField(default=False, verbose_name='当前版本')),
                ('create_by', models.CharField(blank=True, default='', max_length=64, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='datadev.datadevscript', verbose_name='所属脚本')),
            ],
            options={
                'verbose_name': '脚本版本',
                'verbose_name_plural': '脚本版本',
                'db_table': 'datadev_script_version',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='DataDevScriptExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.CharField(max_length=64, unique=True, verbose_name='执行ID')),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('running', '执行中'), ('success', '执行成功'), ('failed', '执行失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='执行状态')),
                ('executor_type', models.CharField(blank=True, default='', max_length=20, verbose_name='执行器类型')),
                ('executor_params', models.JSONField(blank=True, null=True, verbose_name='执行参数')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='执行时长(秒)')),
                ('result_summary', models.JSONField(blank=True, null=True, verbose_name='结果摘要')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('executed_by', models.CharField(blank=True, default='', max_length=64, verbose_name='执行者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='datadev.datadevscript', verbose_name='所属脚本')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='datadev.datadevscriptversion', verbose_name='执行版本')),
            ],
            options={
                'verbose_name': '脚本执行记录',
                'verbose_name_plural': '脚本执行记录',
                'db_table': 'datadev_script_execution',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddIndex(
            model_name='datadevscript',
            index=models.Index(fields=['del_flag'], name='datadev_scr_del_fla_572fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='datadevscript',
            index=models.Index(fields=['script_type'], name='datadev_scr_script__ca9449_idx'),
        ),
        migrations.AddIndex(
            model_name='datadevscript',
            index=models.Index(fields=['status'], name='datadev_scr_status_c5e4d5_idx'),
        ),
        migrations.AddIndex(
            model_name='datadevscript',
            index=models.Index(fields=['owner'], name='datadev_scr_owner_c0c8db_idx'),
        ),
        migrations.AddIndex(
            model_name='datadevscriptversion',
            index=models.Index(fields=['is_current'], name='datadev_scr_is_curr_fda565_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datadevscriptversion',
            unique_together={('script', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='datadevscriptexecution',
            index=models.Index(fields=['status'], name='datadev_scr_status_01dd07_idx'),
        ),
        migrations.AddIndex(
            model_name='datadevscriptexecution',
            index=models.Index(fields=['executed_by'], name='datadev_scr_execute_5c6164_idx'),
        ),
        migrations.AddIndex(
            model_name='datadevscriptexecution',
            index=models.Index(fields=['create_time'], name='datadev_scr_create__611f9a_idx'),
        ),
    ]
