# Generated by Django 5.2.8 on 2026-04-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadevscript',
            name='layer',
            field=models.CharField(blank=True, choices=[('ODS', 'ODS 贴源层'), ('DWD', 'DWD 明细层'), ('DWS', 'DWS 汇总层'), ('ADS', 'ADS 应用层')], db_index=True, default='', help_text='ODS/DWD/DWS/ADS', max_length=10, verbose_name='数仓分层'),
        ),
    ]
