# Generated by Django 5.2.8 on 2026-04-06

from django.db import migrations, models


def mark_current_version_released_for_published_scripts(apps, schema_editor):
    DataDevScript = apps.get_model('datadev', 'DataDevScript')
    for script in DataDevScript.objects.filter(status='published'):
        script.versions.filter(is_current=True).update(is_released=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('datadev', '0002_add_layer_to_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadevscriptversion',
            name='is_released',
            field=models.BooleanField(default=False, verbose_name='正式可用'),
        ),
        migrations.AddIndex(
            model_name='datadevscriptversion',
            index=models.Index(fields=['is_released'], name='datadev_scr_is_rele_833271_idx'),
        ),
        migrations.RunPython(mark_current_version_released_for_published_scripts, noop_reverse),
    ]
