# Generated by Django 5.2.8 on 2026-04-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadev', '0003_add_is_released_to_script_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDevDirectory',
            fields=[
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('directory_id', models.AutoField(primary_key=True, serialize=False, verbose_name='目录ID')),
                ('parent_id', models.IntegerField(default=0, verbose_name='父目录ID')),
                ('ancestors', models.CharField(default='0', max_length=255, verbose_name='祖级列表')),
                ('directory_name', models.CharField(max_length=100, verbose_name='目录名称')),
                ('directory_code', models.CharField(max_length=32, unique=True, verbose_name='目录编码')),
                ('order_num', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '停用')], default='0', max_length=1, verbose_name='状态')),
                ('remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
            ],
            options={
                'verbose_name': '数据目录',
                'verbose_name_plural': '数据目录',
                'db_table': 'datadev_directory',
                'ordering': ['order_num', 'directory_id'],
                'indexes': [models.Index(fields=['parent_id'], name='datadev_dir_parent__6e9fec_idx'), models.Index(fields=['directory_code'], name='datadev_dir_directo_5e40df_idx'), models.Index(fields=['status'], name='datadev_dir_status_d911a7_idx'), models.Index(fields=['del_flag'], name='datadev_dir_del_fla_615002_idx')],
            },
        ),
    ]
