# Generated by Django 5.2.8 on 2026-04-06 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadev', '0004_add_datadev_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadevscript',
            name='directory',
            field=models.ForeignKey(blank=True, help_text='脚本所属数据目录，未指定时使用默认目录（order_num 最小的目录）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scripts', to='datadev.datadevdirectory', verbose_name='所属目录'),
        ),
    ]
