# Generated by Django 5.2.8 on 2026-04-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datadev', '0005_add_directory_to_script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datadevscript',
            name='layer',
        ),
    ]
