# Generated by Django 5.2.8 on 2026-04-18 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadev', '0006_remove_layer_from_script'),
        ('datatask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadevscriptexecution',
            name='task_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_executions', to='datatask.taskinstance', verbose_name='关联任务实例'),
        ),
    ]
