# Generated by Django 5.2.8 on 2026-04-19 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadev', '0007_datadevscriptexecution_task_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDevModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('model_name', models.CharField(max_length=128, verbose_name='模型名称')),
                ('model_code', models.CharField(max_length=64, unique=True, verbose_name='模型编码')),
                ('layer', models.CharField(choices=[('ODS', 'ODS'), ('DWD', 'DWD'), ('DWS', 'DWS'), ('ADS', 'ADS')], max_length=16, verbose_name='数据层级')),
                ('table_name', models.CharField(max_length=255, verbose_name='目标表名')),
                ('schema_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Schema/库名')),
                ('table_comment', models.CharField(max_length=1024, verbose_name='表注释')),
                ('engine_type', models.CharField(choices=[('spark', 'Spark SQL'), ('hive', 'Hive')], default='spark', max_length=16, verbose_name='执行引擎')),
                ('owner', models.CharField(blank=True, default='', max_length=64, verbose_name='负责人')),
                ('description', models.TextField(blank=True, default='', verbose_name='模型说明')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('deployed', '已建表')], default='draft', max_length=20, verbose_name='状态')),
            ],
            options={
                'verbose_name': '数据模型',
                'verbose_name_plural': '数据模型',
                'db_table': 'datadev_model',
                'ordering': ['-update_time', '-create_time'],
                'indexes': [models.Index(fields=['del_flag'], name='datadev_mod_del_fla_c7b32c_idx'), models.Index(fields=['layer'], name='datadev_mod_layer_a736b5_idx'), models.Index(fields=['status'], name='datadev_mod_status_7f306c_idx'), models.Index(fields=['owner'], name='datadev_mod_owner_434c96_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataDevModelField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('ordinal_position', models.IntegerField(default=1, verbose_name='字段顺序')),
                ('field_name', models.CharField(max_length=128, verbose_name='字段名称')),
                ('field_type', models.CharField(max_length=64, verbose_name='字段类型')),
                ('field_comment', models.CharField(blank=True, default='', max_length=512, verbose_name='字段注释')),
                ('is_nullable', models.BooleanField(default=True, verbose_name='是否可空')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_fields', to='datadev.datadevmodel', verbose_name='所属模型')),
            ],
            options={
                'verbose_name': '数据模型字段',
                'verbose_name_plural': '数据模型字段',
                'db_table': 'datadev_model_field',
                'ordering': ['ordinal_position', 'id'],
                'indexes': [models.Index(fields=['del_flag'], name='datadev_mod_del_fla_68486b_idx'), models.Index(fields=['model', 'ordinal_position'], name='datadev_mod_model_i_e6c4ec_idx')],
                'constraints': [models.UniqueConstraint(fields=('model', 'field_name', 'del_flag'), name='datadev_model_field_unique_name')],
            },
        ),
    ]
