# Generated by Django 5.2.8 on 2026-04-19 20:57

from django.db import migrations, models


def backfill_script_engine_type(apps, schema_editor):
    DataDevScript = apps.get_model('datadev', 'DataDevScript')
    DataDevScript.objects.filter(script_type='python').update(engine_type='mvp')
    DataDevScript.objects.filter(script_type='sql', engine_type='').update(engine_type='spark')


class Migration(migrations.Migration):

    dependencies = [
        ('datadev', '0008_datadevmodel_datadevmodelfield'),
        ('datasource', '0003_datasource_connectivity_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadevscript',
            name='engine_type',
            field=models.CharField(choices=[('spark', 'Spark SQL'), ('hive', 'Hive'), ('mvp', 'MVP预演')], default='spark', max_length=16, verbose_name='执行引擎'),
        ),
        migrations.AddIndex(
            model_name='datadevscript',
            index=models.Index(fields=['engine_type'], name='datadev_scr_engine__13fd02_idx'),
        ),
        migrations.RunPython(backfill_script_engine_type, migrations.RunPython.noop),
    ]
