# Generated by Django 5.2.8 on 2026-04-22 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadev', '0009_datadevscript_engine_type_and_more'),
        ('datasource', '0003_datasource_connectivity_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datadevscript',
            options={'ordering': ['-create_time'], 'verbose_name': '加工作业', 'verbose_name_plural': '加工作业'},
        ),
        migrations.AlterModelOptions(
            name='datadevscriptexecution',
            options={'ordering': ['-create_time'], 'verbose_name': '作业执行记录', 'verbose_name_plural': '作业执行记录'},
        ),
        migrations.AlterModelOptions(
            name='datadevscriptversion',
            options={'ordering': ['-version_number'], 'verbose_name': '作业版本', 'verbose_name_plural': '作业版本'},
        ),
        migrations.RemoveField(
            model_name='datadevscript',
            name='directory',
        ),
        migrations.AddField(
            model_name='datadevscript',
            name='script_role',
            field=models.CharField(choices=[('explore', '探索分析'), ('transform', '模型加工'), ('quality', '质量校验'), ('backfill', '数据回刷'), ('python_job', 'Python 作业')], default='explore', max_length=20, verbose_name='作业用途'),
        ),
        migrations.AddField(
            model_name='datadevscript',
            name='target_model',
            field=models.ForeignKey(blank=True, help_text='生产型加工作业建议绑定目标模型，探索脚本可留空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scripts', to='datadev.datadevmodel', verbose_name='目标模型'),
        ),
        migrations.AlterField(
            model_name='datadevscript',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='作业说明'),
        ),
        migrations.AlterField(
            model_name='datadevscript',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='datadevscript',
            name='script_code',
            field=models.CharField(max_length=64, unique=True, verbose_name='作业编码'),
        ),
        migrations.AlterField(
            model_name='datadevscript',
            name='script_name',
            field=models.CharField(max_length=128, verbose_name='作业名称'),
        ),
        migrations.AlterField(
            model_name='datadevscript',
            name='script_type',
            field=models.CharField(choices=[('sql', 'SQL'), ('python', 'Python')], default='sql', max_length=20, verbose_name='作业类型'),
        ),
        migrations.AlterField(
            model_name='datadevscriptexecution',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='datadev.datadevscript', verbose_name='所属作业'),
        ),
        migrations.AlterField(
            model_name='datadevscriptversion',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='datadev.datadevscript', verbose_name='所属作业'),
        ),
        migrations.AddIndex(
            model_name='datadevscript',
            index=models.Index(fields=['script_role'], name='datadev_scr_script__74749b_idx'),
        ),
    ]
