# Generated by Codex on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadev', '0012_delete_datadevscriptexecution'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='datadevmodelfield',
            name='datadev_model_field_unique_name',
        ),
        migrations.AddConstraint(
            model_name='datadevmodelfield',
            constraint=models.UniqueConstraint(
                fields=('model', 'field_name'),
                condition=models.Q(del_flag='0'),
                name='datadev_model_field_unique_name',
            ),
        ),
    ]
