# Generated by Django 5.2.8 on 2025-12-01 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('sql_text', models.TextField(verbose_name='SQL语句')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('status', models.CharField(choices=[('success', '成功'), ('fail', '失败')], default='success', max_length=10, verbose_name='执行状态')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时(ms)')),
                ('error_msg', models.CharField(blank=True, default='', max_length=500, verbose_name='错误信息')),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datasource.datasource', verbose_name='数据源')),
            ],
            options={
                'verbose_name': '数据查询日志',
                'verbose_name_plural': '数据查询日志',
                'db_table': 'datasource_query_log',
                'indexes': [models.Index(fields=['username'], name='datasource__usernam_f69aca_idx'), models.Index(fields=['status'], name='datasource__status_2c1377_idx'), models.Index(fields=['data_source'], name='datasource__data_so_96e741_idx'), models.Index(fields=['del_flag'], name='datasource__del_fla_72c6e9_idx')],
            },
        ),
    ]
