# Generated by Django 5.2.8 on 2026-04-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataintegration', '0004_remove_dataintegrationtask_source_table_snapshot'),
        ('datasource', '0004_phase1_snapshots_and_tasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SourceColumnSnapshot',
        ),
        migrations.DeleteModel(
            name='SourceMetadataCollectionTask',
        ),
        migrations.DeleteModel(
            name='SourceTableSnapshot',
        ),
    ]
