# Generated by Django 5.2.8 on 2026-05-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0010_remove_collection_task_schedule_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='datasource',
            new_name='datasource__name_0faf16_idx',
            old_name='dataasset_d_name_cc0358_idx',
        ),
        migrations.RenameIndex(
            model_name='datasource',
            new_name='datasource__db_type_f93e5e_idx',
            old_name='dataasset_d_db_type_d0e0ab_idx',
        ),
        migrations.RenameIndex(
            model_name='datasource',
            new_name='datasource__status_0eadaf_idx',
            old_name='dataasset_d_status_9cdf07_idx',
        ),
        migrations.RenameIndex(
            model_name='datasource',
            new_name='datasource__del_fla_52451b_idx',
            old_name='dataasset_d_del_fla_891397_idx',
        ),
        migrations.AlterModelTable(
            name='datasource',
            table='datasource_data_source',
        ),
    ]
