# Generated by Django 5.2.8 on 2025-12-02 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasource', '0002_querylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('table_name', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(blank=True, default='', max_length=256)),
                ('notnull', models.BooleanField(default=False)),
                ('default', models.CharField(blank=True, default='', max_length=512)),
                ('primary', models.BooleanField(default=False)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource.datasource')),
            ],
            options={
                'db_table': 'datameta_column',
                'unique_together': {('data_source', 'table_name', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MetaTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('table_name', models.CharField(max_length=256)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource.datasource')),
            ],
            options={
                'db_table': 'datameta_table',
                'unique_together': {('data_source', 'table_name')},
            },
        ),
    ]
