# Generated by Django 5.2.8 on 2026-01-12 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datameta', '0001_initial'),
        ('datasource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaCollectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('task_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='任务ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '采集中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('current_table', models.CharField(blank=True, max_length=256, verbose_name='当前处理表')),
                ('total_tables', models.IntegerField(default=0, verbose_name='总表数')),
                ('collected_tables', models.IntegerField(default=0, verbose_name='已采集表数')),
                ('failed_tables', models.IntegerField(default=0, verbose_name='失败表数')),
                ('database_name', models.CharField(blank=True, max_length=256, verbose_name='数据库名')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('thread_id', models.CharField(blank=True, max_length=64, verbose_name='线程ID')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_tasks', to='datasource.datasource')),
            ],
            options={
                'verbose_name': '元数据采集任务',
                'verbose_name_plural': '元数据采集任务',
                'db_table': 'datameta_collection_task',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['status'], name='datameta_co_status_84da33_idx'), models.Index(fields=['data_source', 'create_time'], name='datameta_co_data_so_0a9c48_idx')],
            },
        ),
    ]
