# Generated by Django 5.2.8 on 2025-12-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datameta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metacolumn',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='metatable',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='metatable',
            name='database',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
