# Generated by Django 5.2.8 on 2025-12-02 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datameta', '0002_metacolumn_comment_metatable_comment_and_more'),
        ('datasource', '0002_querylog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metatable',
            unique_together={('data_source', 'table_name', 'database')},
        ),
    ]
