# Generated by Django 5.2.8 on 2025-12-02 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datameta', '0003_alter_metatable_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='metacolumn',
            name='table',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='datameta.metatable'),
        ),
        migrations.AlterField(
            model_name='metacolumn',
            name='table_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
