# Generated by Django 5.2.8 on 2025-12-02 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datameta', '0004_metacolumn_table_alter_metacolumn_table_name'),
        ('datasource', '0002_querylog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metacolumn',
            unique_together={('data_source', 'table', 'name')},
        ),
        migrations.RemoveField(
            model_name='metacolumn',
            name='table_name',
        ),
    ]
