# Generated by Django 5.2.8 on 2025-12-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datameta', '0005_alter_metacolumn_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metacolumn',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
