# Generated by Django 5.2.8 on 2025-12-10 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataintegration', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='integrationtask',
            new_name='dataintegra_name_f6db92_idx',
            old_name='dataintegra_name_5b2a4e_idx',
        ),
        migrations.RenameIndex(
            model_name='integrationtask',
            new_name='dataintegra_type_c4a711_idx',
            old_name='dataintegra_type_6d3ecb_idx',
        ),
        migrations.RenameIndex(
            model_name='integrationtask',
            new_name='dataintegra_status_30e070_idx',
            old_name='dataintegra_status_3e7c6f_idx',
        ),
        migrations.RenameIndex(
            model_name='integrationtask',
            new_name='dataintegra_del_fla_a98662_idx',
            old_name='dataintegra_del_fla_2b69e7_idx',
        ),
    ]
