# Generated by Django 5.2.8 on 2026-04-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataintegration', '0003_delete_dataintegrationexecutionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataintegrationtask',
            name='source_table_snapshot',
        ),
    ]
