# Generated by Django 5.2.8 on 2026-04-25 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataintegration', '0004_remove_dataintegrationtask_source_table_snapshot'),
        ('datasource', '0005_remove_sourcemetadatacollectiontask_data_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataintegrationtask',
            name='source_datasource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_integration_tasks', to='datasource.datasource', verbose_name='源数据源'),
        ),
        migrations.AlterField(
            model_name='dataintegrationtask',
            name='target_datasource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_integration_tasks', to='datasource.datasource', verbose_name='目标数据源'),
        ),
    ]
