# Generated by Django 5.2.8 on 2026-04-18 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('task_name', models.CharField(max_length=128, verbose_name='任务名称')),
                ('task_code', models.CharField(max_length=128, unique=True, verbose_name='任务编码')),
                ('task_type', models.CharField(choices=[('DATA_SYNC', '数据同步'), ('SQL_COMPUTE', 'SQL计算')], max_length=32, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('paused', '暂停'), ('archived', '归档')], default='active', max_length=20, verbose_name='任务状态')),
                ('source_module', models.CharField(blank=True, default='', max_length=64, verbose_name='来源模块')),
                ('source_record_id', models.BigIntegerField(blank=True, null=True, verbose_name='来源记录ID')),
                ('schedule_type', models.CharField(choices=[('manual', '手动触发'), ('cron', '定时调度'), ('dependency', '依赖触发')], default='manual', max_length=20, verbose_name='调度类型')),
                ('cron_expression', models.CharField(blank=True, default='', max_length=64, verbose_name='Cron表达式')),
                ('owner', models.CharField(blank=True, default='', max_length=64, verbose_name='负责人')),
                ('task_config', models.JSONField(blank=True, default=dict, verbose_name='任务配置')),
                ('last_instance_status', models.CharField(blank=True, default='', max_length=20, verbose_name='最近实例状态')),
                ('last_instance_at', models.DateTimeField(blank=True, null=True, verbose_name='最近运行时间')),
                ('remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
            ],
            options={
                'verbose_name': '统一任务',
                'verbose_name_plural': '统一任务',
                'db_table': 'datatask_task',
                'ordering': ['-update_time', '-id'],
                'indexes': [models.Index(fields=['del_flag', 'task_type'], name='datatask_ta_del_fla_c20680_idx'), models.Index(fields=['del_flag', 'status'], name='datatask_ta_del_fla_d00393_idx'), models.Index(fields=['source_module', 'source_record_id'], name='datatask_ta_source__6edbbc_idx'), models.Index(fields=['owner'], name='datatask_ta_owner_32f3dd_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('del_flag', '0'), ('source_module__gt', ''), ('source_record_id__isnull', False)), fields=('source_module', 'source_record_id'), name='datatask_unique_live_source_task')],
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(blank=True, max_length=64)),
                ('update_by', models.CharField(blank=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_flag', models.CharField(choices=[('0', '正常'), ('1', '删除')], default='0', max_length=1)),
                ('trigger_condition', models.CharField(choices=[('SUCCESS', '上游成功')], default='SUCCESS', max_length=20, verbose_name='触发条件')),
                ('lag_seconds', models.PositiveIntegerField(default=0, verbose_name='延迟秒数')),
                ('remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('downstream_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_dependencies', to='datatask.task', verbose_name='下游任务')),
                ('upstream_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downstream_dependencies', to='datatask.task', verbose_name='上游任务')),
            ],
            options={
                'verbose_name': '任务依赖',
                'verbose_name_plural': '任务依赖',
                'db_table': 'datatask_task_dependency',
                'ordering': ['upstream_task_id', 'downstream_task_id'],
                'indexes': [models.Index(fields=['del_flag'], name='datatask_ta_del_fla_890224_idx'), models.Index(fields=['upstream_task', 'downstream_task'], name='datatask_ta_upstrea_fe9bae_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('del_flag', '0')), fields=('upstream_task', 'downstream_task'), name='datatask_unique_live_dependency'), models.CheckConstraint(condition=models.Q(('upstream_task', models.F('downstream_task')), _negated=True), name='datatask_dependency_not_self')],
            },
        ),
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='实例ID')),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('running', '执行中'), ('success', '执行成功'), ('failed', '执行失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='实例状态')),
                ('trigger_mode', models.CharField(choices=[('manual', '手动触发'), ('schedule', '定时触发'), ('dependency', '依赖触发')], default='manual', max_length=20, verbose_name='触发方式')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='计划触发时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='执行时长(秒)')),
                ('runtime_config', models.JSONField(blank=True, default=dict, verbose_name='运行时配置')),
                ('executor_type', models.CharField(blank=True, default='', max_length=32, verbose_name='执行器类型')),
                ('result_summary', models.JSONField(blank=True, null=True, verbose_name='结果摘要')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('triggered_by', models.CharField(blank=True, default='', max_length=64, verbose_name='触发者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='datatask.task', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '任务实例',
                'verbose_name_plural': '任务实例',
                'db_table': 'datatask_task_instance',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['task', 'status'], name='datatask_ta_task_id_3d04d6_idx'), models.Index(fields=['trigger_mode'], name='datatask_ta_trigger_db2ec0_idx'), models.Index(fields=['create_time'], name='datatask_ta_create__26f6ef_idx')],
            },
        ),
    ]
