# Generated by Django 5.2.8 on 2026-04-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatask', '0002_repair_legacy_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('DATA_SYNC', '数据同步'), ('SQL_COMPUTE', 'SQL计算'), ('ASSET_COLLECTION', '资产采集')], max_length=32, verbose_name='任务类型'),
        ),
    ]
